[package]
name = "jsrs-parser"
version = "0.1.0"
authors = [
    "Saghm Rossi <saghmrossi@gmail.com>",
    "Terry Sun <terrynsun@gmail.com>"
]
build = "build.rs"

[build-dependencies]
lalrpop = "0.7.0"

[dependencies]
nalgebra = "0.3.1"
lalrpop-util = "0.7.0"
