[package]
name = "jsrs-parser"
version = "0.1.0"
authors = ["Saghm Rossi <saghmrossi@gmail.com>"]
build = "build.rs"

[build-dependencies]
lalrpop = "0.6.1"

[dependencies]
nalgebra = "0.3.0"
lalrpop-util = "0.6.1"
